#!/bin/bash
#Faxel
clear
toilet -f pagga         hack_insta         | lolcat
echo "Mise a jour de hack_insta en cours........." | lolcat
echo ""
git pull origin master
echo "Mise à jour de hack_insta terminer........." | lolcat
echo ""
figlet -f small hack_insta a jour!   | lolcat
echo ""
toilet -f mono12 -F border Faxel | lolcat
sleep 3
echo ""
xdg-open https://www.youtube.com/c/FASTERAXEL?sub_confirmation=1
clear
