#!/bin/bash
#Faxel
clear
toilet -f pagga         SECURITY         | lolcat
echo "Mise a jour de Security en cours........." | lolcat
echo ""
git pull origin master
echo "Mise à jour de Security terminer........." | lolcat
echo ""
figlet -f small Security a jour!   | lolcat
echo ""
toilet -f mono12 -F border Faxel | lolcat
sleep 3
echo ""
xdg-open https://www.youtube.com/c/FASTERAXEL?sub_confirmation=1
clear
